config.json: Update to 3.4 buildtools tarball
Fixes diffoscope-native failing in diffoscope tests on workers using buildtools:

  File "/home/pokybuild/yocto-worker/reproducible-ubuntu/build/build-st/tmp/work/x86_64-linux/diffoscope-native/190-r0/recipe-sysroot-native/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: nativepython3: undefined symbol: archive_version_number

Missing or incomplete libarchive module. Try installing your system's 'libarchive' package.

(there is a glibc symbol mismatch hidden in a module compile for libarchive)

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>